"""alter user add batch_date column

Revision ID: 0a5b91ef6475
Revises: eb1a06bfd930
Create Date: 2022-05-03 14:31:42.710007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5b91ef6475'
down_revision = 'eb1a06bfd930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('batch_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'batch_date')
    # ### end Alembic commands ###
